version: "3"
services:
    # start the ganache cli container
    ganache-cli:
        container_name: ganache-cli
        build:
            context: ./docker/ganache-cli
        # note host:container
        #network_mode: "host"
        ports:
            - 8545:8545
        stdin_open: true # docker run -i
        tty: true # docker run -t
    truffle_suite:
        container_name: truffle_suite
        build:
            context: ./docker/truffle-suite
                # volumes
        #network_mode: "host"
        volumes:
            - ".:/workspace"
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t
